export {NewProduct} from './new'
export {ProductDetails} from './details'
export {ProductList} from './list'
export {ProductSummary} from './summary'
export {ProductImage} from './image'
export {ProductSearch} from './search'
